package services

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"mime"
	"os"
	"path/filepath"
	"strings"
	"time"

	"academyprometheus/backend/config"
	"academyprometheus/backend/models"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/rs/zerolog/log"
	"gorm.io/gorm"
)

var ErrObjectNotFound = errors.New("storage object not found")

type PutObjectInput struct {
	Key, ContentType, CacheControl string
	Body                           io.Reader
}

type StoredObject struct {
	Key, Provider, Bucket, ChecksumSHA256 string
	Size                                  int64
}
type ObjectInfo struct {
	Key, ContentType, ChecksumSHA256 string
	Size                             int64
	ModifiedAt                       time.Time
}

type ObjectStorage interface {
	Put(context.Context, PutObjectInput) (StoredObject, error)
	Open(context.Context, string) (io.ReadCloser, ObjectInfo, error)
	Exists(context.Context, string) (bool, error)
	Delete(context.Context, string) error
	Copy(context.Context, string, string) error
	SignedURL(context.Context, string, time.Duration) (string, error)
}

type LocalStorage struct{ Root string }

func (s *LocalStorage) path(key string) (string, error) {
	key = strings.TrimLeft(filepath.ToSlash(key), "/")
	clean := filepath.Clean(filepath.FromSlash(key))
	if clean == "." || strings.HasPrefix(clean, "..") || filepath.IsAbs(clean) {
		return "", fmt.Errorf("invalid object key")
	}
	root, _ := filepath.Abs(s.Root)
	path, _ := filepath.Abs(filepath.Join(root, clean))
	if path != root && !strings.HasPrefix(path, root+string(filepath.Separator)) {
		return "", fmt.Errorf("object key escapes storage root")
	}
	return path, nil
}
func (s *LocalStorage) Put(ctx context.Context, in PutObjectInput) (StoredObject, error) {
	p, err := s.path(in.Key)
	if err != nil {
		return StoredObject{}, err
	}
	if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
		return StoredObject{}, err
	}
	tmp, err := os.CreateTemp(filepath.Dir(p), ".object-*")
	if err != nil {
		return StoredObject{}, err
	}
	defer os.Remove(tmp.Name())
	h := sha256.New()
	n, err := io.Copy(io.MultiWriter(tmp, h), &contextReader{ctx: ctx, r: in.Body})
	if closeErr := tmp.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return StoredObject{}, err
	}
	if err = os.Rename(tmp.Name(), p); err != nil {
		return StoredObject{}, err
	}
	return StoredObject{Key: in.Key, Provider: "local", Size: n, ChecksumSHA256: hex.EncodeToString(h.Sum(nil))}, nil
}
func (s *LocalStorage) Open(_ context.Context, key string) (io.ReadCloser, ObjectInfo, error) {
	p, e := s.path(key)
	if e != nil {
		return nil, ObjectInfo{}, e
	}
	f, e := os.Open(p)
	if os.IsNotExist(e) {
		return nil, ObjectInfo{}, ErrObjectNotFound
	}
	if e != nil {
		return nil, ObjectInfo{}, e
	}
	st, e := f.Stat()
	if e != nil {
		f.Close()
		return nil, ObjectInfo{}, e
	}
	return f, ObjectInfo{Key: key, Size: st.Size(), ModifiedAt: st.ModTime()}, nil
}
func (s *LocalStorage) Exists(ctx context.Context, key string) (bool, error) {
	r, _, e := s.Open(ctx, key)
	if e == ErrObjectNotFound {
		return false, nil
	}
	if e != nil {
		return false, e
	}
	r.Close()
	return true, nil
}
func (s *LocalStorage) Delete(_ context.Context, key string) error {
	p, e := s.path(key)
	if e != nil {
		return e
	}
	e = os.Remove(p)
	if os.IsNotExist(e) {
		return nil
	}
	return e
}
func (s *LocalStorage) Copy(ctx context.Context, a, b string) error {
	r, _, e := s.Open(ctx, a)
	if e != nil {
		return e
	}
	defer r.Close()
	_, e = s.Put(ctx, PutObjectInput{Key: b, Body: r})
	return e
}
func (s *LocalStorage) SignedURL(_ context.Context, _ string, _ time.Duration) (string, error) {
	return "", errors.New("local storage does not issue signed URLs")
}

type R2Storage struct {
	client  *s3.Client
	presign *s3.PresignClient
	bucket  string
}

func NewR2Storage(ctx context.Context, c config.Config, bucket, access, secret string) (*R2Storage, error) {
	if c.R2AccountID == "" || bucket == "" || access == "" || secret == "" {
		return nil, errors.New("R2 is not configured")
	}
	endpoint := "https://" + c.R2AccountID + ".r2.cloudflarestorage.com"
	ac, err := awsconfig.LoadDefaultConfig(ctx, awsconfig.WithRegion("auto"), awsconfig.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(access, secret, "")))
	if err != nil {
		return nil, err
	}
	// R2 is S3-compatible, but optional streaming CRC32 trailers generated by
	// newer AWS SDK releases can be rejected as BadDigest. PutObject does not
	// require that checksum, and storage integrity is verified separately with
	// the SHA-256 digest recorded by this service.
	ac.RequestChecksumCalculation = aws.RequestChecksumCalculationWhenRequired
	ac.ResponseChecksumValidation = aws.ResponseChecksumValidationWhenRequired
	cl := s3.NewFromConfig(ac, func(o *s3.Options) { o.BaseEndpoint = aws.String(endpoint); o.UsePathStyle = true })
	return &R2Storage{client: cl, presign: s3.NewPresignClient(cl), bucket: bucket}, nil
}
func (s *R2Storage) Put(ctx context.Context, in PutObjectInput) (StoredObject, error) {
	tmp, err := os.CreateTemp("", "prometheus-r2-upload-*")
	if err != nil {
		return StoredObject{}, fmt.Errorf("prepare R2 upload: %w", err)
	}
	defer func() {
		_ = tmp.Close()
		_ = os.Remove(tmp.Name())
	}()
	h := sha256.New()
	n, err := io.Copy(io.MultiWriter(tmp, h), &contextReader{ctx: ctx, r: in.Body})
	if err != nil {
		return StoredObject{}, fmt.Errorf("buffer R2 upload: %w", err)
	}
	if _, err := tmp.Seek(0, io.SeekStart); err != nil {
		return StoredObject{}, fmt.Errorf("rewind R2 upload: %w", err)
	}
	out, err := s.client.PutObject(ctx, &s3.PutObjectInput{Bucket: &s.bucket, Key: &in.Key, Body: tmp, ContentLength: aws.Int64(n), ContentType: optionalString(in.ContentType), CacheControl: optionalString(in.CacheControl)})
	if err != nil {
		return StoredObject{}, err
	}
	_ = out
	head, err := s.client.HeadObject(ctx, &s3.HeadObjectInput{Bucket: &s.bucket, Key: &in.Key})
	if err != nil {
		return StoredObject{}, err
	}
	if aws.ToInt64(head.ContentLength) != n {
		return StoredObject{}, fmt.Errorf("R2 upload size mismatch: sent %d bytes, stored %d bytes", n, aws.ToInt64(head.ContentLength))
	}
	return StoredObject{Key: in.Key, Provider: "r2", Bucket: s.bucket, Size: n, ChecksumSHA256: hex.EncodeToString(h.Sum(nil))}, nil
}
func (s *R2Storage) Open(ctx context.Context, key string) (io.ReadCloser, ObjectInfo, error) {
	o, e := s.client.GetObject(ctx, &s3.GetObjectInput{Bucket: &s.bucket, Key: &key})
	if e != nil {
		return nil, ObjectInfo{}, e
	}
	return o.Body, ObjectInfo{Key: key, Size: aws.ToInt64(o.ContentLength), ContentType: aws.ToString(o.ContentType), ModifiedAt: aws.ToTime(o.LastModified)}, nil
}
func (s *R2Storage) Exists(ctx context.Context, key string) (bool, error) {
	_, e := s.client.HeadObject(ctx, &s3.HeadObjectInput{Bucket: &s.bucket, Key: &key})
	if e != nil {
		return false, nil
	}
	return true, nil
}
func (s *R2Storage) Delete(ctx context.Context, key string) error {
	_, e := s.client.DeleteObject(ctx, &s3.DeleteObjectInput{Bucket: &s.bucket, Key: &key})
	return e
}
func (s *R2Storage) Copy(ctx context.Context, a, b string) error {
	src := s.bucket + "/" + a
	_, e := s.client.CopyObject(ctx, &s3.CopyObjectInput{Bucket: &s.bucket, Key: &b, CopySource: &src})
	return e
}
func (s *R2Storage) SignedURL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	o, e := s.presign.PresignGetObject(ctx, &s3.GetObjectInput{Bucket: &s.bucket, Key: &key}, s3.WithPresignExpires(ttl))
	if e != nil {
		return "", e
	}
	return o.URL, nil
}

type R2ObjectSummary struct {
	Key          string
	Size         int64
	LastModified time.Time
	ContentType  string
}

func (s *R2Storage) List(ctx context.Context, prefix string) ([]R2ObjectSummary, error) {
	var all []R2ObjectSummary
	var contToken *string
	for {
		out, err := s.client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{Bucket: &s.bucket, Prefix: aws.String(prefix), ContinuationToken: contToken})
		if err != nil {
			return all, err
		}
		for _, obj := range out.Contents {
			all = append(all, R2ObjectSummary{Key: aws.ToString(obj.Key), Size: aws.ToInt64(obj.Size), LastModified: aws.ToTime(obj.LastModified)})
		}
		if !aws.ToBool(out.IsTruncated) {
			break
		}
		contToken = out.NextContinuationToken
	}
	return all, nil
}
func optionalString(v string) *string {
	if v == "" {
		return nil
	}
	return &v
}

type contextReader struct {
	ctx context.Context
	r   io.Reader
}

func (r *contextReader) Read(p []byte) (int, error) {
	select {
	case <-r.ctx.Done():
		return 0, r.ctx.Err()
	default:
		return r.r.Read(p)
	}
}

func NewObjectStorage(ctx context.Context, c config.Config) (ObjectStorage, error) {
	if c.StorageProvider == "r2" {
		return NewR2Storage(ctx, c, c.R2Bucket, c.R2AccessKeyID, c.R2SecretAccessKey)
	}
	return &LocalStorage{Root: c.StoragePath}, nil
}

func newObjectStorageForStoredObject(ctx context.Context, c config.Config, obj models.StoredObject) (ObjectStorage, error) {
	switch obj.StorageProvider {
	case "r2":
		bucket := fallbackString(obj.Bucket, c.R2Bucket)
		return NewR2Storage(ctx, c, bucket, c.R2AccessKeyID, c.R2SecretAccessKey)
	default:
		return &LocalStorage{Root: c.StoragePath}, nil
	}
}

func EffectiveStorageConfig(ctx context.Context, db *gorm.DB, cfg config.Config) config.Config {
	if db == nil {
		return cfg
	}
	var setting models.Setting
	if err := db.WithContext(ctx).Where("`key` = ?", "storage_provider_active").First(&setting).Error; err == nil {
		provider := strings.ToLower(strings.TrimSpace(setting.Value))
		if provider == "local" || provider == "r2" {
			cfg.StorageProvider = provider
		}
	}
	if strings.TrimSpace(cfg.StorageProvider) == "" {
		cfg.StorageProvider = "local"
	}
	return cfg
}

func NewConfiguredObjectStorage(ctx context.Context, db *gorm.DB, cfg config.Config) (ObjectStorage, config.Config, error) {
	effective := EffectiveStorageConfig(ctx, db, cfg)
	storage, err := NewObjectStorage(ctx, effective)
	return storage, effective, err
}

func ObjectKeyFromPublicPath(publicPath string) string {
	return strings.TrimLeft(filepath.ToSlash(strings.TrimSpace(publicPath)), "/")
}

func ContentTypeForObject(key, configured string) string {
	configured = strings.TrimSpace(strings.ToLower(strings.Split(configured, ";")[0]))
	if configured != "" && configured != "application/octet-stream" {
		return configured
	}
	switch strings.ToLower(filepath.Ext(key)) {
	case ".webp":
		return "image/webp"
	case ".avif":
		return "image/avif"
	case ".jpg", ".jpeg":
		return "image/jpeg"
	case ".png":
		return "image/png"
	case ".gif":
		return "image/gif"
	case ".svg":
		return "image/svg+xml"
	case ".pdf":
		return "application/pdf"
	}
	if detected := mime.TypeByExtension(filepath.Ext(key)); detected != "" {
		return detected
	}
	return "application/octet-stream"
}

func OpenStoredPublicPath(ctx context.Context, db *gorm.DB, cfg config.Config, publicPath string) (io.ReadCloser, ObjectInfo, error) {
	effective := EffectiveStorageConfig(ctx, db, cfg)
	key := ObjectKeyFromPublicPath(publicPath)
	if db != nil {
		var obj models.StoredObject
		if err := db.WithContext(ctx).Where("legacy_path = ? OR object_key = ?", publicPath, key).Order("updated_at desc").First(&obj).Error; err == nil {
			var lastErr error
			storage, storageErr := newObjectStorageForStoredObject(ctx, effective, obj)
			if storageErr == nil {
				reader, info, openErr := storage.Open(ctx, obj.ObjectKey)
				if openErr == nil {
					return reader, info, nil
				}
				lastErr = openErr
			} else {
				lastErr = storageErr
				log.Warn().Str("object_key", obj.ObjectKey).Str("provider", obj.StorageProvider).Err(storageErr).Msg("create storage client for stored object failed")
			}
			if localReader, localInfo, localErr := (&LocalStorage{Root: effective.StoragePath}).Open(ctx, obj.ObjectKey); localErr == nil {
				return localReader, localInfo, nil
			}
			if r2Reader, r2Info, r2Err := openR2PublicObject(ctx, effective, obj.ObjectKey); r2Err == nil {
				_ = db.WithContext(ctx).Model(&obj).Updates(map[string]any{"storage_provider": "r2", "bucket": effective.R2Bucket}).Error
				return r2Reader, r2Info, nil
			}
			if backupReader, backupInfo, backupErr := openBackupR2Object(ctx, effective, obj.ObjectKey); backupErr == nil {
				return backupReader, backupInfo, nil
			}
			return nil, ObjectInfo{}, fmt.Errorf("open stored object %s: %w", obj.ObjectKey, lastErr)
		}
	}
	storage, _, err := NewConfiguredObjectStorage(ctx, db, cfg)
	if err != nil {
		return nil, ObjectInfo{}, err
	}
	reader, info, err := storage.Open(ctx, key)
	if err == nil {
		return reader, info, err
	}
	if effective.StorageProvider == "r2" {
		if localReader, localInfo, localErr := (&LocalStorage{Root: effective.StoragePath}).Open(ctx, key); localErr == nil {
			return localReader, localInfo, nil
		}
		if backupReader, backupInfo, backupErr := openBackupR2Object(ctx, effective, key); backupErr == nil {
			return backupReader, backupInfo, nil
		}
		return nil, ObjectInfo{}, err
	}
	if r2Reader, r2Info, r2Err := openR2PublicObject(ctx, effective, key); r2Err == nil {
		return r2Reader, r2Info, nil
	}
	if backupReader, backupInfo, backupErr := openBackupR2Object(ctx, effective, key); backupErr == nil {
		return backupReader, backupInfo, nil
	}
	return nil, ObjectInfo{}, err
}

func openR2PublicObject(ctx context.Context, cfg config.Config, key string) (io.ReadCloser, ObjectInfo, error) {
	if strings.TrimSpace(cfg.R2Bucket) == "" || strings.TrimSpace(cfg.R2AccessKeyID) == "" || strings.TrimSpace(cfg.R2SecretAccessKey) == "" {
		return nil, ObjectInfo{}, fmt.Errorf("R2 fallback is not configured")
	}
	r2Cfg := cfg
	r2Cfg.StorageProvider = "r2"
	storage, err := NewObjectStorage(ctx, r2Cfg)
	if err != nil {
		return nil, ObjectInfo{}, err
	}
	return storage.Open(ctx, key)
}

func openBackupR2Object(ctx context.Context, cfg config.Config, key string) (io.ReadCloser, ObjectInfo, error) {
	if strings.TrimSpace(cfg.BackupR2Bucket) == "" {
		return nil, ObjectInfo{}, fmt.Errorf("backup R2 fallback is not configured")
	}
	backupCfg := cfg
	backupCfg.StorageProvider = "r2"
	backupCfg.R2Bucket = cfg.BackupR2Bucket
	backupCfg.R2AccessKeyID = fallbackString(cfg.BackupR2AccessKeyID, cfg.R2AccessKeyID)
	backupCfg.R2SecretAccessKey = fallbackString(cfg.BackupR2SecretAccessKey, cfg.R2SecretAccessKey)
	storage, err := NewObjectStorage(ctx, backupCfg)
	if err != nil {
		return nil, ObjectInfo{}, err
	}
	return storage.Open(ctx, key)
}

func DeleteStoredPublicPath(ctx context.Context, db *gorm.DB, cfg config.Config, publicPath string) error {
	key := ObjectKeyFromPublicPath(publicPath)
	if db != nil {
		var obj models.StoredObject
		if err := db.WithContext(ctx).Where("legacy_path = ? OR object_key = ?", publicPath, key).Order("updated_at desc").First(&obj).Error; err == nil {
			storage, storageErr := newObjectStorageForStoredObject(ctx, EffectiveStorageConfig(ctx, db, cfg), obj)
			if storageErr != nil {
				return storageErr
			}
			if err := storage.Delete(ctx, obj.ObjectKey); err != nil {
				return err
			}
			return db.WithContext(ctx).Delete(&obj).Error
		} else if !errors.Is(err, gorm.ErrRecordNotFound) {
			return err
		}
	}
	storage, _, err := NewConfiguredObjectStorage(ctx, db, cfg)
	if err != nil {
		return err
	}
	if err := storage.Delete(ctx, key); err != nil {
		if localErr := (&LocalStorage{Root: cfg.StoragePath}).Delete(ctx, key); localErr == nil {
			return nil
		}
		return err
	}
	return nil
}

func RegisterStoredObject(ctx context.Context, db *gorm.DB, cfg config.Config, stored StoredObject, publicPath, originalName, mimeType, visibility, ownerScope, objectClass string, ownerID uint, expiresAt *time.Time) {
	if db == nil || stored.Key == "" {
		return
	}
	provider := stored.Provider
	if provider == "" {
		provider = cfg.StorageProvider
	}
	if provider == "" {
		provider = "local"
	}
	row := models.StoredObject{
		StorageProvider: provider,
		Bucket:          stored.Bucket,
		ObjectKey:       stored.Key,
		LegacyPath:      publicPath,
		OriginalName:    originalName,
		MimeType:        mimeType,
		SizeBytes:       stored.Size,
		ChecksumSHA256:  stored.ChecksumSHA256,
		Visibility:      fallbackString(visibility, "public"),
		OwnerID:         ownerID,
		OwnerScope:      fallbackString(ownerScope, "admin"),
		ObjectClass:     fallbackString(objectClass, "public"),
		ExpiresAt:       expiresAt,
	}
	_ = db.WithContext(ctx).Where(models.StoredObject{ObjectKey: row.ObjectKey}).Assign(row).FirstOrCreate(&row).Error
}

func fallbackString(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}
